# Permalinks
permalink:           pretty

# Setup
title:               cosy-sun
tagline:             
url:                 http://cosy-sun.github.io
baseurl:             /cosy-sun.github.io
analytics_id:

# Owner/author information
owner:
  name:           Alex Russell
  avatar:         avatar.png
  bio:            "Designer."
  email:          737387998@qq.com
  twitter:        alexanderussell
  github:         alexanderussell
  instagram:      alexanderussell
  dribbble:       alexanderussell
  location:       "Lincoln, NE"


# Custom vars
version:             2.0.0
github:
  repo:              

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Gems
gems:
  - jekyll-paginate
